# Project-wide Gradle settings

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

android.useAndroidX=true

# تعطيل New Architecture (مهم جدًا)
newArchEnabled=true

# تعطيل Hermes مؤقتًا (حل حاسم)
hermesEnabled=true

# خليها الافتراضي أو سيبها
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
